name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: "5.3.5"
    - name: Run tests
      run: cargo test --all
