name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Run six_e tests
      run: cd six_e && cargo test --verbose
