name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Lua
      run: sudo apt-get install lua5.3-dev lua5.3
    - name: Run tests
      run: cargo test --all
